### ISSUE TITLE
Why MachineKey.Protect is being used?

### ISSUE THREAD

**Issue by richardversluis** [ridercz/CsrFence#1]
Hi,

I was looking for a csrf prevention module and I found your library using nuget. Thanks for taking the time for making such important httpmodule available through nuget.

I'm looking through your code to get a better understanding how things work. I was wondering why you are using `MachineKey.Protect()` and Unprotect to encrypt the cookie's token. Why bother to protect the hidden field? Can't we just use the token that is used in the cookie in the hidden field? I'm trying to understand the added value encrypting the hiddenfield value.

Thanks!

**Comment by ridercz** [comment]
The added value is in being signed, not encrypted. The `Protect` method does both and it's easier to use it than write custom signature-only method.

**Comment by richardversluis** [comment]
Thanks ridercz
