### ISSUE TITLE
Possible to invalidate anti-CSRF tokens soon as they're used?

### ISSUE THREAD

**Issue by cemerson** [ridercz/CsrFence#2]
I'm working on getting a .NET web app of mine compliant with a security standard and I installed CSRFence to address a CSRF vulnerablity our penetration test vendor found.  The vendor said CSRFence has helped but there is still an issue. They're now saying: 

> "once a valid anti-CSRF token is generated for a particular account, it can also be used for any other account as well. The back-end should perform the following additional checks: 
> 1. Back-end code should not allow an anti-CSRF token created for a particular account, to be used for another account. Otherwise an attacker can create a token for his own account and use it in a CSRF attack targeting another user. (Mandatory)
> 2. Ideally, the system should invalidate the anti-CSRF token as soon as it is posted to the server. Multiple uses should be disallowed. (Optional)"

Is there a built-in way to configure/use CSRFence to do what they're asking or should I build this functionality into my web app?

**Comment by ridercz** [comment]
Ad 1), CSRFence does exactly that, only it does not tie the validity to user accounts (as it would not work for non-authenticated pages), but uses session cookie with randomly generated identifier instead. Therefore the attack scenario your vendor described is not possible. It is not possible to use token generated for one user to be used by another one, it would defeat the purpose of CSRF protection alltogether.

Ad 2), It would be possible, but it would require semi-persistent storage of used CSRF tokens, which would complicate things a lot, especially when used in a farm. As I am not aware of any attack vector this approach would block, I deem it out of scope.

**Comment by cemerson** [comment]
Thank you, @ridercz. Your advice is very much appreciated. 

Update: Just FYI the vendor reviewed your feedback and they agreed w/your assessment and have retracted the proposed work request. Huge thank you again, sir!
